server:
 port: 8082
 servlet:
  context-path: /api

spring:
 datasource:
  url: jdbc:h2:mem:testdb
  username: sa
  password:
  h2:
   console:
   enabled: true
   path: /h2-console

security:
 oauth2:
  client:
   client-id:  fc4m@r4-$cho0L
   client-secret: fc4m@r4-$ch0oL-Secr3t

jwt:
 secret: jwtS3cr3t@2021
 duration: 43200 #12 horas