server:
 port: 8082
 servlet:
    context-path: /api

spring:
 jpa:
  hibernate:
   ddl-auto: update
 datasource:
  url: jdbc:mysql://localhost:3306/fcamaraproject?useTimezone=true&serverTimezone=UTC
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver

security:
 oauth2:
  client:
   client-id:  fc4m@r4-$cho0L
   client-secret: fc4m@r4-$ch0oL-Secr3t

jwt:
 secret: jwtS3cr3t@2021
 duration: 43200 #12 horas