server:
 port: 8082
 servlet:
    context-path: /api

spring:
 jpa:
  hibernate:
   ddl-auto: update
 datasource:
  url: jdbc:mysql://localhost:3306/fcamaraproject?useTimezone=true&serverTimezone=UTC
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver

 security:
  oauth2:
   client:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}

jwt:
 secret: ${JWT_SECRET}
 duration: ${JWT_DURATION}